name: flutter_application_sync
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  card_swiper: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SpoqahansansneoBold
      fonts:
        - asset: assets/fonts/spoqahansansneo_bold.ttf
    - family: SpoqahansansneoRegular
      fonts:
        - asset: assets/fonts/spoqahansansneo_regular.ttf
    - family: SpoqahansansneoMedium
      fonts:
        - asset: assets/fonts/spoqahansansneo_medium.ttf
